### PR TITLE
Fix issues with upgrading notes for Harbor 12.x.x

### LINKED ISSUE #102: Incorrect upgrading notes for bitnami/harbor to 12.0.0
https://github.com/bitnami/charts-docs/blob/e432d1790cb282ab56e1bceecedfd765eb4e800a/charts/harbor/_upgrade.md.erb#L22

> `service.tls` map has been renamed to `nginx.tls`. To configure TLS termination with Ingress, set `ingress.tls` parameter.

The upgrading notes for Harbor 12.0.0 speaks about "the `ingress.tls` parameter", but I find no such parameter in 12.1.0.

Did it exist in 12.0.0 and was removed in 12.1.0, or did it never exist? Either way, I feel this needs to be clarified in the upgrading notes to make it possible to configure the release correctly.

### PR DESCRIPTION
**Pull request by lindhe**
Please see the messages for each individual commit! :)

Resolves #102 

# Summary

* Replace 12.0.0 with 12.x.x
* Make code markup consistent
* Clarify bullet points
* Fix typos in use of postgresql parameters
* Use explicit container for exec command
* Remove redundant exports
* Replace echo with printenv
* Fix ShellCheck warnings
* Use dynamic numbering of ordered list
* Consistently set --namespace
* Set namespace as a variable
* Guard against accidentally empty variables

### CODE REVIEW

**Comment by lindhe** [comment]
Some remaining questions I have:

1. Do I need to run something to rerender the markdown, or will that be done automatically?
2. Would we get syntax highlighting if we use code fencing instead of indentations for the code snippets?
3. Some changes are down to taste, some are important changes to the guide. Are all fine?

**Review by migruiz4 — CHANGES_REQUESTED** [review]
Hi @lindhe,

Thank you very much for this amazing contribution! Thanks for the details in every change, everything was super clear, and the changes look good to me.

Just one request, could you please update this PR signing the commits?

**Comment by lindhe** [comment]
Sure, will do!

Oops, I pushed after just signing one of them. Hang on...

**Comment by lindhe** [comment]
There we go. :)

**Comment by lindhe** [comment]
There's actually one more thing that's unclear to me, but I don't know what to make of it. It's probably just me missing something...

We explicitly `--set postgresql.image.tag=$CURRENT_PG_VERSION` to keep the same image for the postgresql pod.  And later we `kubectl delete pod harbor-postgresql-0` but AFAICT we never upgrade again with the new version of the sts. Do we intentionally stay at the earlier version?

**Comment by migruiz4** [comment]
Version 12.0.0 included two changes, the standardization of harbor values to be aligned with the rest of the charts catalog, and upgrading PostgreSQL subchart, which also included standardization changes + upgrades PostgreSQL from version 11 to 14.

The PostgreSQL upgrade notes also include a note about this, referencing PostgreSQL documentation about upgrading from version 11 to 14:
https://github.com/bitnami/charts-docs/blob/e432d1790cb282ab56e1bceecedfd765eb4e800a/charts/postgresql/_upgrade.md.erb#L69-L77

I think we should add the same note here to warn users about upgrading PostgreSQL database.

**Comment by lindhe** [comment]
Oh, BTW: Does the markdown rendering on your webpage support syntax highlighting if we put the code sections in code fencing?

**Comment by migruiz4** [comment]
It does! Although I'm not 100% sure about what languages are supported.

Check grafana-operator documentation in case this is what your are looking for: https://docs.bitnami.com/kubernetes/infrastructure/grafana-operator/configuration/deploy-extra-resources/

https://github.com/bitnami/charts-docs/blob/e432d1790cb282ab56e1bceecedfd765eb4e800a/charts/grafana-operator/_deploy_extra_resources.md.erb#L16-L50

**Comment by lindhe** [comment]
> It does! Although I'm not 100% sure about what languages are supported.

Great! I'll see to it!

**Comment by lindhe** [comment]
> Version 12.0.0 included two changes, the standardization of harbor values to be aligned with the rest of the charts catalog, and upgrading PostgreSQL subchart, which also included standardization changes + upgrades PostgreSQL from version 11 to 14.
> 
> The PostgreSQL upgrade notes also include a note about this, referencing PostgreSQL documentation about upgrading from version 11 to 14:
> [...]
> I think we should add the same note here to warn users about upgrading PostgreSQL database.

Very interesting! That clears things up a lot for me! I'll definitely add that notice here as well. And I'll look into the instructions for upgrading database, and see if we can add that too so users may "upgrade fully".

If that's not possible, I may open a PR to https://github.com/bitnami/charts/ to try and make the Chart more aware about what versions it should try and install.

**Comment by migruiz4** [comment]
> I'll investigate what action would be needed to upgrade the database. If it seems easy, I'll add that too so the upgrading notes really describes the full upgrade. Otherwise, I'll leave it as is and we'll merge it (if you still think it looks good).

Pointing the upstream upgrading notes looks good to me. It is a good point to draw the line between chart upgrading and app upgrading, and it is the most trustworthy source for users to find what fits best for their use case.

Thank you very much for your understanding during the code review and the attention to detail!

P.S.: I previously mentioned I wasn't sure about supported code syntax highlighting, but I have a more precise answer: We use Middleman to render markdown templates, and Middleman uses `rouge`, so this would be the list of supported languages: https://github.com/rouge-ruby/rouge/wiki/List-of-supported-languages-and-lexers

**Review by migruiz4 — APPROVED** [review]

**Comment by lindhe** [comment]
When is this expected to go live? :)

**Comment by migruiz4** [comment]
I'm sorry, it was my bad! I forgot to update the documentation pointing to the latest changes.

Here they are: https://docs.bitnami.com/kubernetes/infrastructure/harbor/administration/upgrade/

**Pull request merged**
